[package]
name = "football_simulator"
version = "0.1.0"
authors = ["Ole-Johan Skrede <ojskrede@gmail.com>"]

[dependencies]
select = "0.4"
failure = "0.1"
csv = "1.0"
serde = "1.0"
serde_derive = "1.0"
itertools = "0.7"
indicatif = "0.9"
rayon = "1.0"
time = "0.1"
clap = "2.32"
